name: Handle Data Issue

on:
  issues:
    types: [opened]

jobs:
  handle-data-issue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.body, '__GENERATED_BY_DATA_TOOL__') == true
    steps:
      - name: 添加标签
        uses: actions-cool/issues-helper@v3
        with:
          actions: add-labels
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: data
      - name: 提示缺少附件
        if: contains(github.event.issue.body, 'gjfLeo/summoners-summit/files') == false
        uses: actions-cool/issues-helper@v3
        with:
          actions: create-comment
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            似乎缺少附件，可能没有上传成功，请确认。
