name: Issue Create Comment

on:
  issues:
    types: [opened]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Missing Data File
        if: contains(github.event.issue.body, '__GENERATE_BY_DATA_TOOL__') == true && contains(github.event.issue.body, 'gjfLeo/summoners-summit/files') == false
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            文件似乎没有上传成功，请确认。
